contigs_path: "/path/to/Contigs"
diamond_path: "/path/to/Diamond"
accession2taxadb: "/path/to/accessionTaxa.sql"
names_dmp: "/path/to/names.dmp"
vmr_file: "/path/to/VMR_MSL38_v1.xlsx"
scripts: "/path/to/scripts"
target_taxons:
  Viruses:
    rank: superkingdom
    taxid: 10239
software:
  hsblastn:
    path: "/path/to/hs-blastn"
    index: "/path/to/nt.fna"
    max_hsps: 1
    max_target_seqs: 1
    evalue: "1e-5"
    threads: 1
  megablastn:
    path: "/path/to/blastn"
    index: "/path/to/nt.fna"
    max_hsps: 1
    max_target_seqs: 1
    evalue: "1e-5"
    threads: 1
checkv:
  path: "/path/to/checkv"
  database: "/path/to/checkv-db-v1.5"
  threads: 1
